---
# Configure mandb

- name: service is enabled and started
  service:
    name: "{{ item }}"
    enabled: true
    state: started
  become: true
  loop: "{{ mandb_services_enable }}"
  when: mandb_enable_service
