---
# Template configuration files for mandb

- name: template is copied
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  become: true
  loop: "{{ mandb_templates_copy }}"
  when: mandb_copy_templates
